language: android

cache: false
sudo: false

env:
  global:
    - ADB_INSTALL_TIMEOUT = 8

android:
  components:
    - tools
    - platform-tools
    - extra

    - build-tools-23.0.3
    - android-23

    - sys-img-armeabi-v7a-android-19

before_script:
  - echo no | android create avd --force -n test -t android-19 --abi armeabi-v7a
  - emulator -avd test -no-skin -no-audio -no-window &
  - ./gradlew assembleDebugAndroidTest
  - ./gradlew assembleDebug
  - android-wait-for-emulator
  - adb shell input keyevent 82 &

script: ./gradlew connectedCheck -i --stacktrace
